// Generates five 5-hour test session logs and writes encrypted files
// to the workspace .vscode/logs directory using the same encryption
// parameters as StorageManager (password: 'password').
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SECRET_PASSPHRASE = 'password';
const SALT = 'salty_buffer_tbd';
const KEY = crypto.scryptSync(SECRET_PASSPHRASE, SALT, 32);
const ALGORITHM = 'aes-256-cbc';
const IV_LENGTH = 16;

function formatISO(ts) {
  return new Date(ts).toISOString();
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const sampleWords = ['function','variable','const','let','return','if','else','class','console.log','import','export','test','describe','it','map','filter','reduce','Promise','async','await','handler','component','render','state','props'];
function sampleText(words) {
  let out = [];
  for (let i = 0; i < words; i++) out.push(sampleWords[Math.floor(Math.random() * sampleWords.length)]);
  return out.join(' ');
}

function generateEvents(durationMs, mode) {
  // mode: 'ai', 'manual', 'light', 'balanced', 'heavyManual'
  const events = [];
  const start = Date.now();
  let now = start;
  while (now - start < durationMs) {
    // step 1-20s
    const step = randomInt(1, 20) * 1000;
    now += step;
    const roll = Math.random();
    let ev = { time: formatISO(now), flightTime: String(step), eventType: 'input', fileEdit: '', fileView: '' };
    // choose file names to vary
    const files = ['app.ts','index.tsx','utils.ts','component.jsx','main.py','server.go'];
    const file = files[Math.floor(Math.random() * files.length)];
    ev.fileView = file;
    ev.fileEdit = (Math.random() < 0.8) ? file : '';

    if (mode === 'ai') {
      // mostly AI events
      if (roll < 0.7) {
        ev.eventType = 'ai-paste';
        ev.pasteCharCount = randomInt(50, 600);
        ev.possibleAiDetection = 'NOTE: Generated by AI suggestion';
      } else if (roll < 0.85) {
        ev.eventType = 'ai-replace';
        ev.pasteCharCount = randomInt(20, 300);
      } else if (roll < 0.95) {
        ev.eventType = 'ai-delete';
      } else {
        ev.eventType = 'save';
      }
    } else if (mode === 'manual') {
      if (roll < 0.6) {
        ev.eventType = 'input';
      } else if (roll < 0.75) {
        ev.eventType = 'paste';
        ev.pasteCharCount = randomInt(5, 150);
      } else if (roll < 0.9) {
        ev.eventType = 'delete';
      } else if (roll < 0.95) {
        ev.eventType = 'replace';
        ev.pasteCharCount = randomInt(1, 80);
      } else {
        ev.eventType = 'save';
      }
    } else if (mode === 'light') {
      if (roll < 0.55) ev.eventType = 'input';
      else if (roll < 0.7) { ev.eventType = 'paste'; ev.pasteCharCount = randomInt(5,120); }
      else if (roll < 0.82) { ev.eventType = 'ai-paste'; ev.pasteCharCount = randomInt(40,220); ev.possibleAiDetection = 'NOTE: Assistant suggestion used'; }
      else if (roll < 0.9) ev.eventType = 'delete';
      else ev.eventType = 'save';
    } else if (mode === 'balanced') {
      if (roll < 0.4) ev.eventType = 'input';
      else if (roll < 0.55) { ev.eventType = 'paste'; ev.pasteCharCount = randomInt(10,200); }
      else if (roll < 0.75) { ev.eventType = 'ai-paste'; ev.pasteCharCount = randomInt(20,300); ev.possibleAiDetection = 'NOTE: Suggested code inserted'; }
      else if (roll < 0.9) ev.eventType = 'delete';
      else ev.eventType = 'save';
    } else if (mode === 'heavyManual') {
      if (roll < 0.7) ev.eventType = 'input';
      else if (roll < 0.85) { ev.eventType = 'paste'; ev.pasteCharCount = randomInt(5,120); }
      else if (roll < 0.95) ev.eventType = 'delete';
      else { ev.eventType = 'ai-paste'; ev.pasteCharCount = randomInt(20,150); ev.possibleAiDetection = 'NOTE: small assistant snippet used'; }
    }

    // occasional focus changes and durations
    if (Math.random() < 0.02) {
      events.push({ time: formatISO(now-500), flightTime: '0', eventType: 'focusChange', fileEdit: '', fileView: 'Explorer' });
    }
    if (Math.random() < 0.005) {
      events.push({ time: formatISO(now-250), flightTime: '0', eventType: 'focusDuration', fileEdit: '', fileView: ev.fileView });
    }

    events.push(ev);
  }
  return events;
}

function buildSession(sessionNumber, mode, durationMs) {
  const header = {
    sessionHeader: {
      sessionNumber,
      startedBy: 'developer',
      project: 'devproject',
      startTime: formatISO(Date.now() - durationMs),
      metadata: { vscodeVersion: 'test', startTimestamp: formatISO(Date.now() - durationMs), extensionVersion: '0.0.0-test' }
    }
  };
  const events = generateEvents(durationMs, mode);
  return Object.assign({}, header, { events });
}

function encryptBuffer(buf) {
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, KEY, iv);
  const encrypted = Buffer.concat([cipher.update(buf), cipher.final()]);
  return Buffer.concat([iv, encrypted]);
}

function writeLogs() {
  const fiveHours = 5 * 60 * 60 * 1000;
  const workspaceLogs = path.join(process.cwd(), '.vscode', 'logs');
  if (!fs.existsSync(workspaceLogs)) fs.mkdirSync(workspaceLogs, { recursive: true });

  const specs = [
    { name: 'developer-devproject-Session2-integrity.log', mode: 'ai' },
    { name: 'developer-devproject-Session3-integrity.log', mode: 'manual' },
    { name: 'developer-devproject-Session4-integrity.log', mode: 'light' },
    { name: 'developer-devproject-Session5-integrity.log', mode: 'balanced' },
    { name: 'developer-devproject-Session6-integrity.log', mode: 'heavyManual' }
  ];

  for (let i = 0; i < specs.length; i++) {
    const s = specs[i];
    console.log('Generating', s.name, 'mode=', s.mode);
    const session = buildSession(i + 2, s.mode, fiveHours);
    const plain = JSON.stringify(session, null, 2);
    const outPath = path.join(workspaceLogs, s.name);
    const enc = encryptBuffer(Buffer.from(plain, 'utf8'));
    fs.writeFileSync(outPath, enc);
    console.log('Wrote encrypted log to', outPath, 'size=', enc.length);
  }
}

writeLogs();

console.log('Done. Generated 5 encrypted 5-hour logs in .vscode/logs');
