name: CI

on:
  push:
    branches:
      - main
      - "dev/**"
      - "test/**"
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    # DEFINE THE MATRIX
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      # Fail-fast: false ensures that if an OS fails, the others continue
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      #LINUX SPECIFIC SETUP (XVFB)
      # linxu doesnt have a display server, so we need to install and run Xvfb for tests that require a GUI
      - name: Install Xvfb (Linux Only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # RUN TESTS
      # linux uses xvfb-run. On Mac/Windows, we just run npm test.
      - name: Run Tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a npm test
          else
            npm test
          fi
        shell: bash

      # COMPILE
      - name: Build
        run: npm run build
